=== houser/polish_api_zadanie_testowe/HoldInfo/HoldInfo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- W3C Schema generated by XMLSpy v2019 rel. 3 sp1 (x64) (http://www.altova.com) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" vc:minVersion="1.1">
	<xs:element name="HoldInfo">
		<xs:complexType>
			<xs:all>
				<xs:element name="mcc" type="xs:string" minOccurs="0"/>
				<xs:element name="amount">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:pattern value="((0|([1-9][0-9]*))\.[0-9]{2,2})"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="itemId">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="64"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="auxData" minOccurs="0">
					<xs:complexType>
						<xs:all>
							<xs:any processContents="skip" minOccurs="0" maxOccurs="unbounded"/>
						</xs:all>
						<xs:anyAttribute processContents="skip"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="currency" minOccurs="0">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="3"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="tradeDate" type="xs:string" minOccurs="0"/>
				<xs:element name="description" minOccurs="0">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="140"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="transactionType" minOccurs="0">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="100"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="sender" minOccurs="0">
					<xs:complexType mixed="true">
						<xs:all>
							<xs:element name="accountMassPayment" type="xs:string" minOccurs="0"/>
							<xs:element name="nameAddress" minOccurs="0">
								<xs:complexType mixed="true">
									<xs:all>
										<xs:element name="item" minOccurs="0" maxOccurs="unbounded"/>
										<xs:element name="value" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="item" maxOccurs="4">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:maxLength value="35"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:all>
									<xs:anyAttribute processContents="skip"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="item" minOccurs="0" maxOccurs="unbounded"/>
							<xs:element name="bank" minOccurs="0">
								<xs:complexType mixed="true">
									<xs:all>
										<xs:element name="countryCode" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:maxLength value="3"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="item" minOccurs="0" maxOccurs="unbounded"/>
										<xs:element name="bicOrSwift" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:maxLength value="11"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="name" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:maxLength value="70"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="code" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:maxLength value="10"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="address" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="item" maxOccurs="4">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:maxLength value="35"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:all>
									<xs:anyAttribute processContents="skip"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="accountNumber" type="xs:string" minOccurs="0"/>
						</xs:all>
						<xs:anyAttribute processContents="skip"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="initiator" minOccurs="0">
					<xs:complexType mixed="true">
						<xs:all>
							<xs:element name="item" minOccurs="0" maxOccurs="unbounded"/>
							<xs:element name="value" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="item" maxOccurs="4">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:maxLength value="35"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:all>
						<xs:anyAttribute processContents="skip"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="recipient" minOccurs="0">
					<xs:complexType mixed="true">
						<xs:all>
							<xs:element name="accountMassPayment" type="xs:string" minOccurs="0"/>
							<xs:element name="nameAddress" minOccurs="0">
								<xs:complexType mixed="true">
									<xs:all>
										<xs:element name="item" minOccurs="0" maxOccurs="unbounded"/>
										<xs:element name="value" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="item" maxOccurs="4">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:maxLength value="35"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:all>
									<xs:anyAttribute processContents="skip"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="item" minOccurs="0" maxOccurs="unbounded"/>
							<xs:element name="bank" minOccurs="0">
								<xs:complexType mixed="true">
									<xs:all>
										<xs:element name="countryCode" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:maxLength value="3"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="item" minOccurs="0" maxOccurs="unbounded"/>
										<xs:element name="bicOrSwift" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:maxLength value="11"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="name" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:maxLength value="70"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="code" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:maxLength value="10"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="address" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="item" maxOccurs="4">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:maxLength value="35"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:all>
									<xs:anyAttribute processContents="skip"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="accountNumber" type="xs:string" minOccurs="0"/>
						</xs:all>
						<xs:anyAttribute processContents="skip"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="holdExpirationDate" type="xs:string" minOccurs="0"/>
				<xs:any processContents="skip" minOccurs="0" maxOccurs="unbounded"/>
			</xs:all>
			<xs:anyAttribute processContents="skip"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== houser/polish_api_zadanie_testowe/HoldInfo/HoldInfo.xml
<?xml version="1.0" encoding="utf-8"?>
<HoldInfo xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="HoldInfo.xsd">
	<mcc>string</mcc>
	<amount>661.80</amount>
	<itemId>string</itemId>
	<auxData/>
	<currency>A</currency>
	<tradeDate>string</tradeDate>
	<description>string</description>
	<transactionType>string</transactionType>
	<sender>
		<accountMassPayment>string</accountMassPayment>
		<nameAddress>
			<item/>
			<item/>
			<value>
				<item>string</item>
				<item>string</item>
				<item>string</item>
			</value>
		</nameAddress>
		<item/>
		<item/>
		<bank>
			<countryCode>AB</countryCode>
			<item/>
			<item/>
			<item/>
			<item/>
			<name>string</name>
			<address>
				<item>string</item>
				<item>string</item>
				<item>string</item>
				<item>string</item>
			</address>
		</bank>
		<accountNumber>string</accountNumber>
	</sender>
	<initiator>
		<item/>
		<item/>
		<item/>
		<value>
			<item>string</item>
		</value>
	</initiator>
	<recipient>
		<accountMassPayment>string</accountMassPayment>
		<nameAddress>
			<item/>
			<item/>
		</nameAddress>
		<item/>
		<item/>
		<item/>
		<item/>
		<item/>
		<bank>
			<name>string</name>
			<code>string</code>
		</bank>
		<accountNumber>string</accountNumber>
	</recipient>
	<holdExpirationDate>string</holdExpirationDate>
</HoldInfo>
