=== houser/polish_api_zadanie_testowe/ItemInfoBase/ItemInfoBase.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!-- W3C Schema generated by XMLSpy v2019 rel. 3 sp1 (x64) (http://www.altova.com) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="ItemInfoBase">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="type"/>
				<xs:element ref="required" maxOccurs="unbounded"/>
				<xs:element ref="properties"/>
				<xs:element ref="description"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="additionalProperties">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="type"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="amount">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="type"/>
				<xs:element ref="description"/>
				<xs:element ref="pattern"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="auxData">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="type"/>
				<xs:element ref="description"/>
				<xs:element ref="additionalProperties"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="currency">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="type"/>
				<xs:element ref="description"/>
				<xs:element ref="maxLength"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="description">
		<xs:complexType mixed="true">
			<xs:sequence minOccurs="0">
				<xs:element ref="type"/>
				<xs:element ref="description"/>
				<xs:element ref="maxLength"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="format">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="date-time"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="itemId">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="type"/>
				<xs:element ref="description"/>
				<xs:element ref="maxLength"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="maxLength">
		<xs:simpleType>
			<xs:restriction base="xs:short">
				<xs:enumeration value="100"/>
				<xs:enumeration value="140"/>
				<xs:enumeration value="3"/>
				<xs:enumeration value="64"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="mcc">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="type"/>
				<xs:element ref="description"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="pattern">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="^(0|([1-9][0-9]{0,}))\.\d{2}$"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="properties">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="itemId"/>
				<xs:element ref="amount"/>
				<xs:element ref="currency"/>
				<xs:element ref="description"/>
				<xs:element ref="transactionType"/>
				<xs:element ref="tradeDate"/>
				<xs:element ref="mcc"/>
				<xs:element ref="auxData"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="required">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="amount"/>
				<xs:enumeration value="itemId"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="tradeDate">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="type"/>
				<xs:element ref="format"/>
				<xs:element ref="description"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="transactionType">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="type"/>
				<xs:element ref="description"/>
				<xs:element ref="maxLength"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="type">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="object"/>
				<xs:enumeration value="string"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
</xs:schema>

=== houser/polish_api_zadanie_testowe/ItemInfoBase/ItemInfoBase.xml
<?xml version="1.0" encoding="UTF-8"?>
<ItemInfoBase xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ItemInfoBase.xsd">
	<type>object</type>
	<required>amount</required>
	<required>itemId</required>
	<properties>
		<itemId>
			<type>string</type>
			<description>ID elementu (transakcji lub blokadzie) nadany przez ASPSP / Element (transaction or hold) ID (ASPSP)</description>
			<maxLength>64</maxLength>
		</itemId>
		<amount>
			<type>string</type>
			<description>Kwota transakcji / Amount of the transaction</description>
			<pattern>^(0|([1-9][0-9]{0,}))\.\d{2}$</pattern>
		</amount>
		<currency>
			<type>string</type>
			<description>Kod ISO waluty transakcji / Currency (ISO)</description>
			<maxLength>3</maxLength>
		</currency>
		<description>
			<type>string</type>
			<description>Tytuł transakcji / Description of the transaction</description>
			<maxLength>140</maxLength>
		</description>
		<transactionType>
			<type>string</type>
			<description>Typ transakcji / Transaction type</description>
			<maxLength>100</maxLength>
		</transactionType>
		<tradeDate>
			<type>string</type>
			<format>date-time</format>
			<description>Data operacji, YYYY-MM-DDThh:mm:ss[.mmm] / Date of the operation</description>
		</tradeDate>
		<mcc>
			<type>string</type>
			<description>Kod dla każdej transakcji/operacji wykonanej przy użyciu karty / A code of each transaction performed by card</description>
		</mcc>
		<auxData>
			<type>object</type>
			<description>Klasa mapy &lt;string, string&gt; / Map (Dictionary) class</description>
			<additionalProperties>
				<type>string</type>
			</additionalProperties>
		</auxData>
	</properties>
	<description>Klasa bazowa informacji o elemencie (transakcji lub blokadzie) / Element (transaction or hold) Information Base Class</description>
</ItemInfoBase>
