=== houser/polish_api_zadanie_testowe/PaymentEEARequestBundled/PaymentEEARequestBundled.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- W3C Schema generated by XMLSpy v2019 rel. 3 sp1 (x64) (http://www.altova.com) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" vc:minVersion="1.1">
	<xs:element name="PaymentEEARequestBundled">
		<xs:complexType>
			<xs:all>
				<xs:element name="recipient">
					<xs:complexType mixed="true">
						<xs:all>
							<xs:element name="countryCode">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="3"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="nameAddress">
								<xs:complexType mixed="true">
									<xs:all>
										<xs:element name="item" minOccurs="0" maxOccurs="unbounded"/>
										<xs:element name="value" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="item" maxOccurs="4">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:maxLength value="35"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:all>
									<xs:anyAttribute processContents="skip"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="item" minOccurs="0" maxOccurs="unbounded"/>
							<xs:element name="accountNumber">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="34"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
						</xs:all>
						<xs:anyAttribute processContents="skip"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="sender">
					<xs:complexType mixed="true">
						<xs:all>
							<xs:element name="nameAddress" minOccurs="0">
								<xs:complexType mixed="true">
									<xs:all>
										<xs:element name="item" minOccurs="0" maxOccurs="unbounded"/>
										<xs:element name="value" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="item" maxOccurs="4">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:maxLength value="35"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:all>
									<xs:anyAttribute processContents="skip"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="item" minOccurs="0" maxOccurs="unbounded"/>
							<xs:element name="accountNumber" minOccurs="0">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="34"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
						</xs:all>
						<xs:anyAttribute processContents="skip"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="transferData">
					<xs:complexType>
						<xs:all>
							<xs:element name="amount">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:pattern value="((0|([1-9][0-9]*))\.[0-9]{2,2})"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="description">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="140"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="executionDate" type="xs:string" minOccurs="0"/>
							<xs:element name="currency">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="3"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:any processContents="skip" minOccurs="0" maxOccurs="unbounded"/>
						</xs:all>
						<xs:anyAttribute processContents="skip"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="tppTransactionId">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="64"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="deliveryMode">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="ExpressD0"/>
							<xs:enumeration value="StandardD1"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="system">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="SEPA"/>
							<xs:enumeration value="InstantSEPA"/>
							<xs:enumeration value="Target"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="hold" type="xs:boolean" minOccurs="0"/>
				<xs:element name="executionMode" minOccurs="0">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="Immediate"/>
							<xs:enumeration value="FutureDated"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:any processContents="skip" minOccurs="0" maxOccurs="unbounded"/>
			</xs:all>
			<xs:anyAttribute processContents="skip"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== houser/polish_api_zadanie_testowe/PaymentEEARequestBundled/PaymentEEARequestBundled.xml
<?xml version="1.0" encoding="utf-8"?>
<PaymentEEARequestBundled xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" xsi:noNamespaceSchemaLocation="PaymentEEARequestBundled.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <recipient>
    <countryCode>A</countryCode>
    <nameAddress>
      <item />
      <value>
        <item>string</item>
        <item>string</item>
        <item>string</item>
        <item>string</item>
      </value>
    </nameAddress>
    <item />
    <accountNumber>string</accountNumber>
  </recipient>
  <sender>
    <nameAddress>
      <value>
        <item>string</item>
        <item>string</item>
        <item>string</item>
      </value>
    </nameAddress>
    <item />
    <item />
    <item />
    <accountNumber>string</accountNumber>
  </sender>
  <transferData>
    <amount>3.59</amount>
    <description>string</description>
    <executionDate>string</executionDate>
    <currency>A</currency>
  </transferData>
  <tppTransactionId>string</tppTransactionId>
  <deliveryMode>ExpressD0</deliveryMode>
  <system>InstantSEPA</system>
  <hold>true</hold>
  <executionMode>FutureDated</executionMode>
</PaymentEEARequestBundled>
